### PR TITLE
Corrects the name of two contact methods, adds text re: friendly name

### PR DESCRIPTION
**Pull request by phmiller**
Corrects the name of two contact methods, adds text to explain what user friendly display name is

1. Updates all instances of "contact.getState()" to "contact.getStatus()"
2. Updates all instances of "contact.getStateDuration()" to "contact.getStatusDuration()"
3. Adds description to mentions of user friendly display name to explain that this is the agent's first name

### CODE REVIEW

**Comment by phmiller** [comment]
@jagadeeshaby This PR largely overlaps with PR [https://github.com/aws/amazon-connect-streams/pull/39](https://github.com/aws/amazon-connect-streams/pull/39). The only diff is the little bit of extra text around the user friendly display name. Do you want me to update this PR to remove the contact.getState/getStateDuration parts or close this and open a brand new PR?

**Comment by phmiller** [comment]
@jagadeeshaby Can you elaborate on the agent providing anything as a display name? Where can an agent do that?

**Comment by jagadeeshaby** [comment]
Sorry I meant that firstname could be anything (user friendly display name) while creating the agent on admin website - as we do not validate for the correctness (in most cases yes it will match the agents real first name)

I just wanted to avoid the confusion between Agents real first name and the user friendly display name!.

**Comment by phmiller** [comment]
I'm going to close this out. Most of it has been covered already.

**Comment by jagadeeshaby** [comment]
Thank you.

**Pull request closed without merging**
